# Generated by Django 2.0.10 on 2019-01-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='language',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
