# Generated by Django 2.0.10 on 2019-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190201_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_pk', models.IntegerField()),
                ('pastebin_pk', models.IntegerField()),
            ],
        ),
    ]
