# Generated by Django 2.0.10 on 2019-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
