# Generated by Django 2.0.10 on 2019-02-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_pastebin_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
