# Generated by Django 2.0.10 on 2019-02-06 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0013_auto_20190206_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='pastebin',
        ),
        migrations.AddField(
            model_name='vote',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
