# Generated by Django 2.0.10 on 2019-02-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20190206_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
