# Generated by Django 2.0.10 on 2019-02-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20190223_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
